### ISSUE TITLE
Internal server error: exception

### ISSUE THREAD

**Issue by RAbraham** [pedestal/pedestal-ions-sample#4]
Hi,
Thank you for posting this repo!
I get the error "Internal server error: exception.%", code 500 when I do the curl. On testing it locally, the following error was shown:

```
ERROR ion-sample.service  - {:msg "Value not found for keys [:io.pedestal.ions/params :db-name]", :keys [:io.pedestal.ions/params :db-name], :m {:response nil, :io.pedestal.ions/app-info {:app-name "blackdog", :deployment-group "blackdog-dev-Compute-1459KLKOL55DG"}, :io.pedestal.interceptor.chain/stack (#Interceptor{:name :ion-sample.service/datomic-interceptor} #Interceptor{:name :io.pedestal.ions/datomic-params-interceptor} #Interceptor{:name :io.pedestal.http.route/router} #Interceptor{:name :io.pedestal.http.ring-middlewares/resource} #Interceptor{:name :io.pedestal.http.secure-headers/secure-headers} #Interceptor{:name :io.pedestal.http.route/method-param} #Interceptor{:name :io.pedestal.http.route/path-params-decoder} #Interceptor{:name :io.pedestal.http.route/query-params} #Interceptor{:name :io.pedestal.http.ring-middlewares/content-type-interceptor} #Interceptor{:name :io.pedestal.http/not-found} #Interceptor{:name :io.pedestal.http/log-request} #Interceptor{:name :io.pedestal.ions/ring-response} #Interceptor{:name :io.pedestal.ions/terminator-injector}), :request {:server-port 0, :server-name "localhost", :remote-addr "127.0.0.1", :uri "/pets", :scheme "http", :request-method :get, :path-info "/pets", :path-params {}, :url-for #object[clojure.lang.Delay 0x73dbb666 {:status :pending, :val nil}]}, :bindings {#'io.pedestal.http.route/*url-for* #object[clojure.lang.Delay 0x73dbb666 {:status :pending, :val nil}]}, :io.pedestal.interceptor.chain/terminators (#object[io.pedestal.ions$fn__16177$fn__16178 0x3c809ee7 "io.pedestal.ions$fn__16177$fn__16178@3c809ee7"]), :route {:path "/pets", :method :get, :path-re #"/\Qpets\E", :path-parts ["pets"], :interceptors [#Interceptor{:name :io.pedestal.ions/datomic-params-interceptor} #Interceptor{:name :ion-sample.service/datomic-interceptor} #Interceptor{:name :io.pedestal.http.body-params/body-params} #Interceptor{:name :io.pedestal.http/json-body} #Interceptor{:name }], :route-name :ion-sample.service/pets, :path-params {}, :io.pedestal.http.route.prefix-tree/satisfies-constraints? #object[clojure.core$constantly$fn__5394 0x1492d58d "clojure.core$constantly$fn__5394@1492d58d"]}, :io.pedestal.ions/env-map {:env :dev}, :io.pedestal.interceptor.chain/queue #object[clojure.lang.PersistentQueue 0x57a36189 "clojure.lang.PersistentQueue@cb660c4d"], :url-for #object[clojure.lang.Delay 0x73dbb666 {:status :pending, :val nil}], :io.pedestal.interceptor.chain/execution-id 2, :io.pedestal.ions/params {}}, :line 60}
ERROR io.pedestal.ions  - {:msg "error response triggered", :context {:response nil, :io.pedestal.ions/app-info {:app-name "blackdog", :deployment-group "blackdog-dev-Compute-1459KLKOL55DG"}, :io.pedestal.interceptor.chain/stack (#Interceptor{:name :io.pedestal.ions/terminator-injector}), :request {:server-port 0, :server-name "localhost", :remote-addr "127.0.0.1", :uri "/pets", :scheme "http", :request-method :get, :path-info "/pets", :path-params {}, :url-for #object[clojure.lang.Delay 0x73dbb666 {:status :pending, :val nil}]}, :bindings {#'io.pedestal.http.route/*url-for* #object[clojure.lang.Delay 0x73dbb666 {:status :pending, :val nil}]}, :io.pedestal.interceptor.chain/terminators (#object[io.pedestal.ions$fn__16177$fn__16178 0x3c809ee7 "io.pedestal.ions$fn__16177$fn__16178@3c809ee7"]), :route {:path "/pets", :method :get, :path-re #"/\Qpets\E", :path-parts ["pets"], :interceptors [#Interceptor{:name :io.pedestal.ions/datomic-params-interceptor} #Interceptor{:name :ion-sample.service/datomic-interceptor} #Interceptor{:name :io.pedestal.http.body-params/body-params} #Interceptor{:name :io.pedestal.http/json-body} #Interceptor{:name }], :route-name :ion-sample.service/pets, :path-params {}, :io.pedestal.http.route.prefix-tree/satisfies-constraints? #object[clojure.core$constantly$fn__5394 0x1492d58d "clojure.core$constantly$fn__5394@1492d58d"]}, :io.pedestal.ions/env-map {:env :dev}, :url-for #object[clojure.lang.Delay 0x73dbb666 {:status :pending, :val nil}], :io.pedestal.interceptor.chain/execution-id 2, :io.pedestal.ions/params {}}, :line 96}
clojure.lang.ExceptionInfo: clojure.lang.ExceptionInfo in Interceptor :ion-sample.service/datomic-interceptor - Value not found for keys [:io.pedestal.ions/params :db-name]
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invokeStatic(chain.clj:35)
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invoke(chain.clj:32)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:57)
	at io.pedestal.interceptor.chain$try_f.invoke(chain.clj:44)
	at io.pedestal.interceptor.chain$process_all_with_binding.invokeStatic(chain.clj:171)
	at io.pedestal.interceptor.chain$process_all_with_binding.invoke(chain.clj:146)
	at io.pedestal.interceptor.chain$process_all$fn__10789.invoke(chain.clj:188)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at io.pedestal.interceptor.chain$process_all.invokeStatic(chain.clj:186)
	at io.pedestal.interceptor.chain$process_all.invoke(chain.clj:182)
	at io.pedestal.interceptor.chain$enter_all.invokeStatic(chain.clj:235)
	at io.pedestal.interceptor.chain$enter_all.invoke(chain.clj:229)
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:379)
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352)
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:389)
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352)
	at io.pedestal.ions$ion_provider$fn__16217.invoke(ions.clj:176)
	at user$eval16672.invokeStatic(NO_SOURCE_FILE:12)
	at user$eval16672.invoke(NO_SOURCE_FILE:12)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7025)
	at clojure.core$eval.invokeStatic(core.clj:3206)
	at clojure.core$eval.invoke(core.clj:3202)
	at clojure.main$repl$read_eval_print__8572$fn__8575.invoke(main.clj:243)
	at clojure.main$repl$read_eval_print__8572.invoke(main.clj:243)
	at clojure.main$repl$fn__8581.invoke(main.clj:261)
	at clojure.main$repl.invokeStatic(main.clj:261)
	at clojure.main$repl_opt.invokeStatic(main.clj:325)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Value not found for keys [:io.pedestal.ions/params :db-name]
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at ion_sample.service$get_in_or_throw.invokeStatic(service.clj:61)
	at ion_sample.service$get_in_or_throw.invoke(service.clj:55)
	at ion_sample.service$fn__16649.invokeStatic(service.clj:68)
	at ion_sample.service$fn__16649.invoke(service.clj:66)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:54)
	... 37 common frames omitted
INFO  io.pedestal.ions  - {:msg "sending error", :message "Internal server error: exception.", :line 77}
FileNotFoundException Internal server error: exception. (No such file or directory)  java.io.FileInputStream.open (FileInputStream.java:-2)
```

I checked my parameter store and I see the value `db-name`. Note, in my special case, I have a different stack name and application name so I wrote the value `pet-store` to both paths just to be safe. 

When I hard coded the value `pet-store`, it worked when I did the curl(though not when I do it locally, which I'll post as another ticket)

**Comment by ddeaguiar** [comment]
Looks like the underlying issue was identified in #6.
