### ISSUE TITLE
Testing Locally Fails for slurp on Get /pets. Unable to connect to localhost:8182

### ISSUE THREAD

**Issue by RAbraham** [pedestal/pedestal-ions-sample#6]
Hi,
I was trying to test locally the `slurp` on `get` `/pets` which works using `curl` via the API Gateway but it fails locally. As you can see below, the call to `/` succeeds with `Hello World`.
```
pedestal-ions-sample git:(master) clj -Adev:log
Clojure 1.9.0
(require '[ion-sample.ion :as ion]
         '[ion-sample.service :as service])
...
nil
user=> (def h (ion/handler service/service))
#'user/h
>(h {:server-port    0
           :server-name    "localhost"
           :remote-addr    "127.0.0.1"
           :uri            "/"
           :scheme         "http"
           :request-method :get
           :headers        {}})
INFO  io.pedestal.http  - {:msg "GET /", :line 80}
{:status 200, :headers {"Strict-Transport-Security" "max-age=31536000; includeSubdomains", "X-Frame-Options" "DENY", "X-Content-Type-Options" "nosniff", "X-XSS-Protection" "1; mode=block", "X-Download-Options" "noopen", "X-Permitted-Cross-Domain-Policies" "none", "Content-Security-Policy" "object-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:;", "Content-Type" "text/plain"}, :body "Hello World!"}
>(slurp (:body (h {:server-port    0
               :server-name    "localhost"
               :remote-addr    "127.0.0.1"
               :uri            "/pets"
               :scheme         "http"
               :request-method :get})))
INFO  io.pedestal.http  - {:msg "GET /pets", :line 80}
Reflection warning, cognitect/hmac_authn.clj:80:12 - call to static method encodeHex on org.apache.commons.codec.binary.Hex can't be resolved (argument types: unknown, java.lang.Boolean).
Reflection warning, cognitect/hmac_authn.clj:80:3 - call to java.lang.String ctor can't be resolved.
INFO  org.eclipse.jetty.util.log  - Logging initialized @89353ms to org.eclipse.jetty.util.log.Slf4jLog
ERROR io.pedestal.ions  - {:msg "error response triggered", :context {:response nil, :io.pedestal.ions/app-info {:app-name "blackdog", :deployment-group "blackdog-dev-Compute-1459KLKOL55DG"}, :io.pedestal.interceptor.chain/stack (#Interceptor{:name :io.pedestal.ions/terminator-injector}), :request {:server-port 0, :server-name "localhost", :remote-addr "127.0.0.1", :uri "/pets", :scheme "http", :request-method :get, :path-info "/pets", :path-params {}, :url-for #object[clojure.lang.Delay 0x4a402ba3 {:status :pending, :val nil}]}, :bindings {#'io.pedestal.http.route/*url-for* #object[clojure.lang.Delay 0x4a402ba3 {:status :pending, :val nil}]}, :io.pedestal.interceptor.chain/terminators (#object[io.pedestal.ions$fn__16177$fn__16178 0x1a8b2ab3 "io.pedestal.ions$fn__16177$fn__16178@1a8b2ab3"]), :route {:path "/pets", :method :get, :path-re #"/\Qpets\E", :path-parts ["pets"], :interceptors [#Interceptor{:name :io.pedestal.ions/datomic-params-interceptor} #Interceptor{:name :ion-sample.service/datomic-interceptor} #Interceptor{:name :io.pedestal.http.body-params/body-params} #Interceptor{:name :io.pedestal.http/json-body} #Interceptor{:name }], :route-name :ion-sample.service/pets, :path-params {}, :io.pedestal.http.route.prefix-tree/satisfies-constraints? #object[clojure.core$constantly$fn__5394 0x37e628c0 "clojure.core$constantly$fn__5394@37e628c0"]}, :io.pedestal.ions/env-map {:env :dev}, :url-for #object[clojure.lang.Delay 0x4a402ba3 {:status :pending, :val nil}], :io.pedestal.interceptor.chain/execution-id 2, :io.pedestal.ions/params {:db-name "pet-store"}}, :line 96}
clojure.lang.ExceptionInfo: clojure.lang.ExceptionInfo in Interceptor :ion-sample.service/datomic-interceptor - Unable to connect to localhost:8182
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invokeStatic(chain.clj:35)
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invoke(chain.clj:32)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:57)
	at io.pedestal.interceptor.chain$try_f.invoke(chain.clj:44)
	at io.pedestal.interceptor.chain$process_all_with_binding.invokeStatic(chain.clj:171)
	at io.pedestal.interceptor.chain$process_all_with_binding.invoke(chain.clj:146)
	at io.pedestal.interceptor.chain$process_all$fn__10789.invoke(chain.clj:188)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at io.pedestal.interceptor.chain$process_all.invokeStatic(chain.clj:186)
	at io.pedestal.interceptor.chain$process_all.invoke(chain.clj:182)
	at io.pedestal.interceptor.chain$enter_all.invokeStatic(chain.clj:235)
	at io.pedestal.interceptor.chain$enter_all.invoke(chain.clj:229)
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:379)
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352)
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:389)
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352)
	at io.pedestal.ions$ion_provider$fn__16217.invoke(ions.clj:176)
	at user$eval16672.invokeStatic(NO_SOURCE_FILE:11)
	at user$eval16672.invoke(NO_SOURCE_FILE:11)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7025)
	at clojure.core$eval.invokeStatic(core.clj:3206)
	at clojure.core$eval.invoke(core.clj:3202)
	at clojure.main$repl$read_eval_print__8572$fn__8575.invoke(main.clj:243)
	at clojure.main$repl$read_eval_print__8572.invoke(main.clj:243)
	at clojure.main$repl$fn__8581.invoke(main.clj:261)
	at clojure.main$repl.invokeStatic(main.clj:261)
	at clojure.main$repl_opt.invokeStatic(main.clj:325)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Unable to connect to localhost:8182
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at datomic.client.impl.cloud$get_s3_auth_path.invokeStatic(cloud.clj:175)
	at datomic.client.impl.cloud$get_s3_auth_path.invoke(cloud.clj:166)
	at datomic.client.impl.cloud$create_client.invokeStatic(cloud.clj:207)
	at datomic.client.impl.cloud$create_client.invoke(cloud.clj:190)
	at clojure.lang.Var.invoke(Var.java:381)
	at datomic.client.api.impl$dynarun.invokeStatic(impl.clj:19)
	at datomic.client.api.impl$dynarun.invoke(impl.clj:16)
	at datomic.client.api.impl$dynacall.invokeStatic(impl.clj:26)
	at datomic.client.api.impl$dynacall.invoke(impl.clj:23)
	at datomic.client.api.async$client.invokeStatic(async.clj:66)
	at datomic.client.api.async$client.invoke(async.clj:62)
	at datomic.client.api.sync$client.invokeStatic(sync.clj:77)
	at datomic.client.api.sync$client.invoke(sync.clj:75)
	at clojure.lang.Var.invoke(Var.java:381)
	at datomic.client.api.impl$dynarun.invokeStatic(impl.clj:19)
	at datomic.client.api.impl$dynarun.invoke(impl.clj:16)
	at datomic.client.api.impl$dynacall.invokeStatic(impl.clj:26)
	at datomic.client.api.impl$dynacall.invoke(impl.clj:23)
	at datomic.client.api$client.invokeStatic(api.clj:87)
	at datomic.client.api$client.invoke(api.clj:54)
	at datomic.client.api$client.invokeStatic(api.clj:84)
	at datomic.client.api$client.invoke(api.clj:54)
	at ion_sample.service$fn__16638.invokeStatic(service.clj:28)
	at ion_sample.service$fn__16638.invoke(service.clj:26)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$memoize$fn__6586.doInvoke(core.clj:6273)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at ion_sample.service$get_connection.invokeStatic(service.clj:49)
	at ion_sample.service$get_connection.invoke(service.clj:45)
	at ion_sample.service$fn__16649.invokeStatic(service.clj:82)
	at ion_sample.service$fn__16649.invoke(service.clj:79)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:54)
	... 37 common frames omitted
INFO  io.pedestal.ions  - {:msg "sending error", :message "Internal server error: exception.", :line 77}
FileNotFoundException Internal server error: exception. (No such file or directory)  java.io.FileInputStream.open (FileInputStream.java:-2)
```

**Comment by hkrishnan** [comment]
I am getting the same error.  Any ideas?  Thanks.

**Comment by daemianmack** [comment]
Based on...

`Unable to connect to localhost:8182`

it sounds like your local setup is missing the [Datomic access proxy](https://docs.datomic.com/cloud/operation/howto.html#datomic-access) that provides access from localhost to within the Datomic Cloud VPC.

**Comment by hkrishnan** [comment]
Thank you for the response.  I was actually running as stated in that doc.  However, I downloaded the latest version and run the "bash datomic-access client [system] commad.

Then on ERPL, I get the same error. The difference this is that I am not getting the error "Unable to connect to localhost:8182" on the terminal screen.

(slurp (:body (h {:server-port    0
                  :server-name    "localhost"
                  :remote-addr    "127.0.0.1"
                  :uri            "/pets"
                  :scheme         "http"
                  :request-method :get})))


Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
Not Found (No such file or directory)

**Comment by hkrishnan** [comment]
From the bastion service:

debug1: channel 2: new [dynamic-tcpip]
channel 2: open failed: administratively prohibited: open failed

**Comment by hkrishnan** [comment]
I think I figured out the problem.  The Pedestal ion sample uses app-name to create the access url.  In my case, the app-name and the datomic system name are different.
